#!/usr/bin/env python
"""Generate docs/RULES.md from the live rule registry.

The rule catalogue is documentation that must never drift from the code, so it
is generated rather than written. Run this after any rule change.

Usage:
    python scripts/build_rules_doc.py            # write docs/RULES.md
    python scripts/build_rules_doc.py --check    # exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fabric_iq import RULESET_VERSION  # noqa: E402
from fabric_iq.models import ObjectType, Severity  # noqa: E402
from fabric_iq.rules import registry  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(REPO_ROOT, "docs", "RULES.md")

SEVERITY_MARK = {
    Severity.BLOCKING: "🔴 blocking",
    Severity.MAJOR: "🟠 major",
    Severity.MINOR: "🟡 minor",
    Severity.INFO: "⚪ info",
}

OBJECT_TITLE = {
    ObjectType.TENANT: "Tenant",
    ObjectType.WORKSPACE: "Workspace",
    ObjectType.SEMANTIC_MODEL: "Semantic Model",
    ObjectType.REPORT: "Report",
    ObjectType.DATA_AGENT: "Fabric Data Agent",
}


def _escape(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def render() -> str:
    lines = [
        "# Rule Catalogue",
        "",
        "> Generated by `python scripts/build_rules_doc.py`. Do not edit by hand.",
        "",
        f"Ruleset version: `{RULESET_VERSION}` — {len(registry)} rules.",
        "",
        "A **blocking** failure caps the object score at 39 and revokes eligibility.",
        "A **major** failure caps it at 59. Missing evidence yields `NOT_EVALUATED`,",
        "which lowers confidence without moving the score.",
        "",
        "## Summary",
        "",
        "| Object | Rules | Blocking | Major |",
        "|--------|-------|----------|-------|",
    ]

    for object_type in OBJECT_TITLE:
        rules = registry.for_type(object_type)
        if not rules:
            continue
        blocking = sum(1 for r in rules if r.severity is Severity.BLOCKING)
        major = sum(1 for r in rules if r.severity is Severity.MAJOR)
        lines.append(f"| {OBJECT_TITLE[object_type]} | {len(rules)} | {blocking} | {major} |")

    for object_type, title in OBJECT_TITLE.items():
        rules = sorted(registry.for_type(object_type), key=lambda r: r.id)
        if not rules:
            continue
        lines += [
            "",
            f"## {title}",
            "",
            "| ID | Check | Dimension | Severity | Effort | Owner | Remediation |",
            "|----|-------|-----------|----------|--------|-------|-------------|",
        ]
        for rule in rules:
            lines.append(
                f"| `{rule.id}` | {_escape(rule.title)} | {rule.dimension.value} | "
                f"{SEVERITY_MARK.get(rule.severity, rule.severity.value)} | "
                f"{rule.effort.value} | {_escape(rule.owner_role) or '—'} | "
                f"{_escape(rule.remediation)} |"
            )

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()

    content = render()

    if args.check:
        if not os.path.exists(TARGET):
            print("docs/RULES.md is missing; run python scripts/build_rules_doc.py")
            return 1
        with open(TARGET, encoding="utf-8") as handle:
            current = handle.read()
        if current != content:
            print("docs/RULES.md is stale; run python scripts/build_rules_doc.py")
            return 1
        print("docs/RULES.md is up to date.")
        return 0

    os.makedirs(os.path.dirname(TARGET), exist_ok=True)
    with open(TARGET, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    print(f"Wrote {TARGET} ({len(registry)} rules).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
